### ISSUE TITLE
2.3.0 Issue - pm2 displays 'Miners  -11'

### ISSUE THREAD

**Issue by procloud** [cazala/coin-hive-stratum#81]
curious, but still going strong.

1 low hash (and possible some other connects) shows miner count going negative in pm2, but api call to /stats shows actual number

**Comment by cazala** [comment]
should be fixed in `v2.3.4`

**Comment by adamdupuis** [comment]
I am still seeing negative miner counts. Works just fine though :)

**Comment by cazala** [comment]
which version are you running?

you can check this by doing `cat node_modules/coin-hive-stratum/package.json` the version is at the very bottom.

**Comment by adamdupuis** [comment]
Said I was running 2.3.0, but I had just ran install on the package a few hours before. Apologies, I must have done something wrong. I am now on 2.5.8.

Thanks for your hard work @cazala
